#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Asanka B.L. Resume
url: 'http://blasanka.github.io/'
baseurl: '/my_resume' #change it according to your repository name
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: ceramic # blue turquoise green berry orange ceramic

# Tracker
analytics: 

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 127.0.0.1
safe: false